CideryOrganizer/Controllers/ApplesController.cs
using Microsoft.AspNetCore.Mvc;
using CideryOrganizer.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace CideryOrganizer.Controllers
{
  [Authorize]
  public class ApplesController : Controller
  {
    private readonly CideryOrganizerContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public ApplesController(UserManager<ApplicationUser> userManager, CideryOrganizerContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userApples = _db.Apples.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userApples);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Apple apple)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      apple.User = currentUser;
      _db.Apples.Add(apple);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }  
    public ActionResult Details(int id)
    {
      var thisApple = _db.Apples
        .Include(apple => apple.Makers)
        .ThenInclude(join => join.Maker)
        .Include(apple => apple.Ciders)
        .ThenInclude(join => join.Cider)
        .Include(apple => apple.Styles)
        .ThenInclude(join => join.Style)
        .FirstOrDefault(apple => apple.AppleId == id);
      return View(thisApple);
    }
    public ActionResult Edit(int id)
    {
      var thisApple = _db.Apples.FirstOrDefault(apples => apples.AppleId == id);
      ViewBag.MakerId = new SelectList(_db.Makers, "MakerId", "MakerName");
      ViewBag.StyleId = new SelectList(_db.Styles, "StyleId", "StyleName");
      ViewBag.CiderId = new SelectList(_db.Ciders, "CiderId", "CiderName");
      return View(thisApple);
    }

    [HttpPost]
    public ActionResult Edit(Apple apple, int MakerId, int StyleId, int CiderId)
    {
      if (MakerId != 0)
      {
        _db.AppleMaker.Add(new AppleMaker(){ MakerId = MakerId, AppleId = apple.AppleId });
      }
      if (CiderId != 0)
      {
        _db.AppleCider.Add(new AppleCider(){ CiderId = CiderId, AppleId = apple.AppleId });
      }
      if (StyleId != 0)
      {
        _db.AppleStyle.Add(new AppleStyle(){ StyleId = StyleId, AppleId = apple.AppleId });
      }
      _db.Entry(apple).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = apple.AppleId });
    }
    public ActionResult Delete(int id)
    {
      var thisApple = _db.Apples.FirstOrDefault(apples => apples.AppleId == id);
      return View(thisApple);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisApple = _db.Apples.FirstOrDefault(apples => apples.AppleId == id);
      _db.Apples.Remove(thisApple);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteMaker(int appleId, int joinId)
    {
      var joinEntry = _db.AppleMaker.FirstOrDefault(entry => entry.AppleMakerId == joinId);
      _db.AppleMaker.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = appleId});
    }
    public ActionResult AddMaker(int id)
    {
      var thisApple = _db.Apples.FirstOrDefault(apples => apples.AppleId == id);
      ViewBag.MakerId = new SelectList(_db.Makers, "MakerId", "MakerName");
      return View(thisApple);
    }
    [HttpPost]
    public ActionResult AddMaker(Apple apple, int MakerId)
    {
      if (MakerId != 0)
      {
      _db.AppleMaker.Add(new AppleMaker() { MakerId = MakerId, AppleId = apple.AppleId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = apple.AppleId});
    }
    [HttpPost]
    public ActionResult DeleteCider(int appleId, int joinId)
    {
      var joinEntry = _db.AppleCider.FirstOrDefault(entry => entry.AppleCiderId == joinId);
      _db.AppleCider.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = appleId});
    }
    public ActionResult AddCider(int id)
    {
      var thisApple = _db.Apples.FirstOrDefault(apples => apples.AppleId == id);
      ViewBag.CiderId = new SelectList(_db.Ciders, "CiderId", "CiderName");
      return View(thisApple);
    }
    [HttpPost]
    public ActionResult AddCider(Apple apple, int CiderId)
    {
      if (CiderId != 0)
      {
      _db.AppleCider.Add(new AppleCider() { CiderId = CiderId, AppleId = apple.AppleId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = apple.AppleId});
    }

    [HttpPost]
    public ActionResult DeleteStyle(int appleId, int joinId)
    {
      var joinEntry = _db.AppleStyle.FirstOrDefault(entry => entry.AppleStyleId == joinId);
      _db.AppleStyle.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = appleId});
    }
    public ActionResult AddStyle(int id)
    {
      var thisApple = _db.Apples.FirstOrDefault(apples => apples.AppleId == id);
      ViewBag.StyleId = new SelectList(_db.Styles, "StyleId", "StyleName");
      return View(thisApple);
    }
    [HttpPost]
    public ActionResult AddStyle(Apple apple, int StyleId)
    {
      if (StyleId != 0)
      {
      _db.AppleStyle.Add(new AppleStyle() { StyleId = StyleId, AppleId = apple.AppleId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = apple.AppleId});
    }
  }
}

CideryOrganizer/Controllers/CidersController.cs
using Microsoft.AspNetCore.Mvc;
using CideryOrganizer.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace CideryOrganizer.Controllers
{
  [Authorize]
  public class CidersController : Controller
  {
    private readonly CideryOrganizerContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public CidersController(UserManager<ApplicationUser> userManager, CideryOrganizerContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userCiders = _db.Ciders.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userCiders);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Cider cider)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      cider.User = currentUser;
      _db.Ciders.Add(cider);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }    
    public ActionResult Details(int id)
    {
      var thisCider = _db.Ciders
        .Include(cider => cider.Makers)
        .ThenInclude(join => join.Maker)
        .Include(cider => cider.Apples)
        .ThenInclude(join => join.Apple)
        .Include(cider => cider.Styles)
        .ThenInclude(join => join.Style)
        .FirstOrDefault(cider => cider.CiderId == id);
      return View(thisCider);
    }
    public ActionResult Edit(int id)
    {
      var thisCider = _db.Ciders.FirstOrDefault(ciders => ciders.CiderId == id);
      ViewBag.MakerId = new SelectList(_db.Makers, "MakerId", "MakerName");
      ViewBag.StyleId = new SelectList(_db.Styles, "StyleId", "StyleName");
      ViewBag.AppleId = new SelectList(_db.Apples, "AppleId", "AppleName");
      return View(thisCider);
    }

    [HttpPost]
    public ActionResult Edit(Cider cider, int MakerId, int StyleId, int AppleId)
    {
      if (MakerId != 0)
      {
        _db.CiderMaker.Add(new CiderMaker(){ MakerId = MakerId, CiderId = cider.CiderId });
      }
      if (AppleId != 0)
      {
        _db.AppleCider.Add(new AppleCider(){ AppleId = AppleId, CiderId = cider.CiderId });
      }
      if (StyleId != 0)
      {
        _db.CiderStyle.Add(new CiderStyle(){ StyleId = StyleId, CiderId = cider.CiderId });
      }
      _db.Entry(cider).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = cider.CiderId });
    }
    public ActionResult Delete(int id)
    {
      var thisCider = _db.Ciders.FirstOrDefault(ciders => ciders.CiderId == id);
      return View(thisCider);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCider = _db.Ciders.FirstOrDefault(ciders => ciders.CiderId == id);
      _db.Ciders.Remove(thisCider);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteMaker(int ciderId, int joinId)
    {
      var joinEntry = _db.CiderMaker.FirstOrDefault(entry => entry.CiderMakerId == joinId);
      _db.CiderMaker.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = ciderId});
    }
    public ActionResult AddMaker(int id)
    {
      var thisCider = _db.Ciders.FirstOrDefault(ciders => ciders.CiderId == id);
      ViewBag.MakerId = new SelectList(_db.Makers, "MakerId", "MakerName");
      return View(thisCider);
    }
    [HttpPost]
    public ActionResult AddMaker(Cider cider, int MakerId)
    {
      if (MakerId != 0)
      {
      _db.CiderMaker.Add(new CiderMaker() { MakerId = MakerId, CiderId = cider.CiderId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = cider.CiderId});
    }
    [HttpPost]
    public ActionResult DeleteApple(int ciderId, int joinId)
    {
      var joinEntry = _db.AppleCider.FirstOrDefault(entry => entry.AppleCiderId == joinId);
      _db.AppleCider.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = ciderId});
    }
    public ActionResult AddApple(int id)
    {
      var thisCider = _db.Ciders.FirstOrDefault(ciders => ciders.CiderId == id);
      ViewBag.AppleId = new SelectList(_db.Apples, "AppleId", "AppleName");
      return View(thisCider);
    }
    [HttpPost]
    public ActionResult AddCider(Cider cider, int AppleId)
    {
      if (AppleId != 0)
      {
      _db.AppleCider.Add(new AppleCider() { AppleId = AppleId, CiderId = cider.CiderId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = cider.CiderId});
    }

    [HttpPost]
    public ActionResult DeleteStyle(int ciderId, int joinId)
    {
      var joinEntry = _db.CiderStyle.FirstOrDefault(entry => entry.CiderStyleId == joinId);
      _db.CiderStyle.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = ciderId});
    }
    public ActionResult AddStyle(int id)
    {
      var thisCider = _db.Ciders.FirstOrDefault(ciders => ciders.CiderId == id);
      ViewBag.StyleId = new SelectList(_db.Styles, "StyleId", "StyleName");
      return View(thisCider);
    }
    [HttpPost]
    public ActionResult AddStyle(Cider cider, int StyleId)
    {
      if (StyleId != 0)
      {
      _db.CiderStyle.Add(new CiderStyle() { StyleId = StyleId, CiderId = cider.CiderId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = cider.CiderId});
    }
  }
}

CideryOrganizer/Views/Types/Details.cshtml
@{
  Layout = "_Layout";
}
@model CideryOrganizer.Models.Type;
<br><br>
<div class="container">
<h1>@Html.DisplayFor(model => model.TypeName)</h1>
<hr>
  <div class="row">
    <div class="col-sm">
    @if(Model.Ciders.Count == 0)
    {
      <p>This type does not have any ciders.</p>
    }
    else
    {
      <h4>Ciders: </h4>
      @foreach(var join in Model.Ciders)
      {
        <p>@Html.ActionLink($"{join.Cider.CiderName}", "Details", "Ciders", new { id = join.Cider.CiderId }, new { @class="list-detail"})</p>
        @using (Html.BeginForm("DeleteCider", "Types"))
        {
          @Html.Hidden("typeId", @join.TypeId)
          @Html.Hidden("joinId", @join.TypeCiderId)
          <input style="margin-top:-30px" type="submit" value="Delete" class="btn btn-outline-warning btn-sm" />
        }
      }
    }
    <br>
    @if(Model.Apples.Count == 0)
    {
      <p>This type does not have any apples currently assigned.</p>
    }
    else
    {
      <h4>Apple:</h4>
      @foreach(var join in Model.Apples)
      {
        <p>@Html.ActionLink($"{join.Apple.AppleTitle}", "Details", "Apples", new { id = join.Apple.AppleId }, new { @class="list-detail"})</p>
        @using (Html.BeginForm("DeleteApple", "Types"))
        {
          @Html.Hidden("typeId", @join.TypeId)
          @Html.Hidden("joinId", @join.TypeAppleId)
          <input style="margin-top:-30px" type="submit" value="Delete" class="btn btn-outline-warning btn-xs" />
        }
      }
    }
<hr>
<br>

    <p>@Html.ActionLink("Add a Apple", "AddApple", "Types", new { id = Model.TypeId } , new {@class="btn btn-outline-info btn-sm btn-block"})</p>
    <p>@Html.ActionLink("Add a Cider", "AddCider", "Types", new { id = Model.TypeId } , new {@class="btn btn-outline-success btn-sm btn-block"})</p>
    <br>  

  @* back button *@

    <a style="float:left" href="/Types" class="btn btn-outline-dark btn-sm"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-left-square-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm9.5 8.5a.5.5 0 0 0 0-1H5.707l2.147-2.146a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708-.708L5.707 8.5H11.5z"/>
    </svg></a>

  @* edit button *@

    <a style="float:right" href="/Types/Edit/@Model.TypeId" class="btn btn-outline-dark btn-sm"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pen-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M13.498.795l.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z"/>
    </svg></a> 
  
  @* delete button *@

    <a style="float:right; margin-right:7px;" href="/Types/Delete/@Model.TypeId" class="btn btn-outline-dark btn-sm"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
    </svg></a>
    </div>

    <div class="col-sm">

    </div>
    <div class="col-sm">

    </div>
  </div>
</div>